### ISSUE TITLE
Suggestion: Less than one potion at a time

### ISSUE THREAD

**Issue by IchBinGelangweilt** [unregistered/will-save#4]
I use duolingo a lot, so I've already amassed hundreds of potions. This means there is really no limit to how much time I spend on the sites I've blacklisted. It would be nice if I could set it to give me a fraction of a potion for each session, so I might have to do ten practices to earn a potion instead of one.

**Comment by unregistered** [comment]
Wow, very impressive! Can you achieve the same thing by setting it to earn a potion every 30 exp or 50 exp? That would cut your potions down by a factor

**Comment by unregistered** [comment]
Whoops, that's not an option yet. I think it makes more sense to do it that way.

**Comment by unregistered** [comment]
New feature was added in 1.2.0
